ALTER DATABASE MOME_db CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;

USE MOME_db;

-- Create dimension tables first
CREATE TABLE MOME_profil_nexon_depart_dim(
	ID_ORGUNIT VARCHAR(255) PRIMARY KEY,
	NAME_ORGUNIT VARCHAR(255) NOT NULL,
	VALIDFROM_ORGUNIT VARCHAR(255) NOT NULL,
	VALIDTO_ORGUNIT VARCHAR(255),
	PATH_ORGUNIT VARCHAR(255) NOT NULL,
	LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
	
CREATE TABLE MOME_profil_ad_dim(
	CN VARCHAR(255) PRIMARY KEY,
	LASTNAME VARCHAR(255),
	FIRSTNAME VARCHAR(255),
	MAIL VARCHAR(255),
	LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE MOME_profil_nexon_dim(
	PERSONID VARCHAR(255) PRIMARY KEY,
	USERID_USERS VARCHAR(255),
	DISPLAYNAME_USERS VARCHAR(255),
	USEREMAILADDRESSES_USERS VARCHAR(255),
	USERACCOUNTNAMES_USERS VARCHAR(255),
	BIRTHDATE_PERSON VARCHAR(255),
	PERSONALTAXNUMBER_PERSON VARCHAR(255),
	SOCIALSECURITYNUMBER_PERSON VARCHAR(255),
	OKTATOIAZONOSITO_PERSON VARCHAR(255),
	GENDER_PERSON VARCHAR(255),
	CN VARCHAR(255),
	LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
	
CREATE TABLE MOME_profil_neptun_dim(
	NEPTUN VARCHAR(255) PRIMARY KEY,
	CN VARCHAR(255),
	LASTNAME VARCHAR(255),
	FIRSTNAME VARCHAR(255),
	PRINTNAME VARCHAR(255),
	OM_ID VARCHAR(255),
	BORNDATE VARCHAR(255),
	BORNPLACE VARCHAR(255),
	BORNCOUNTY VARCHAR(255),
	TAJ VARCHAR(255),
	SEX VARCHAR(255),
	TAX_NUMBER VARCHAR(255),
	LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create Fact Table
CREATE TABLE MOME_profil_fact(
	PERSONID VARCHAR(8) NOT NULL,
	NEPTUN VARCHAR(9) NOT NULL,
	CN_student VARCHAR(20) NOT NULL,
	CN_staff VARCHAR(20) NOT NULL,
	STATUS VARCHAR(255) NOT NULL,
	STATUS_SOURCE ENUM('NEPTUN', 'NEXON', 'AD') NOT NULL,
	STATUS_BEGIN VARCHAR(10) NOT NULL,
	STATUS_END VARCHAR(10) NOT NULL,
	DEPARTMENT VARCHAR(255) NOT NULL,
	DEPARTMENT_ID VARCHAR(8),
	END_RESULT VARCHAR(255),
	TENURE_TYPE VARCHAR(255),
	QUALIFICATION VARCHAR(255),
	TRAINING_LEVEL VARCHAR(255),
	DIPLOMA_RESULT VARCHAR(255),
	DIPLOMA_ID VARCHAR(255),
	PHD_ID VARCHAR(255),
	LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	FOREIGN KEY (DEPARTMENT_ID) REFERENCES MOME_profil_nexon_depart_dim(ID_ORGUNIT),
	FOREIGN KEY (NEPTUN) REFERENCES MOME_profil_neptun_dim(NEPTUN),
	FOREIGN KEY (PERSONID) REFERENCES MOME_profil_nexon_dim(PERSONID),
	FOREIGN KEY (CN_student) REFERENCES MOME_profil_ad_dim(CN),
	FOREIGN KEY (CN_staff) REFERENCES MOME_profil_ad_dim(CN),
	PRIMARY KEY (NEPTUN, PERSONID, CN_student, CN_staff, STATUS_SOURCE, STATUS, STATUS_BEGIN, STATUS_END, DEPARTMENT)
);
